# Generated by Django 6.0.6 on 2026-06-14 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("muflopping", "0003_list"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "units",
                "ordering": ["order", "name"],
            },
        ),
    ]
