# Generated by Django 6.0.6 on 2026-06-28 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("muflopping", "0006_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="muflopping.unit",
            ),
        ),
    ]
