# Generated by Django 6.0.6 on 2026-06-28 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("muflopping", "0007_product_unit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="unit",
        ),
    ]
